version: '3'

services:
    server:
        container_name: djproject
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./Dockerfile
        entrypoint: /code/entrypoint.sh
        volumes:
            - static_volume:/code/staticfiles
        expose:
            - 8000     
        environment:
            DEBUG: "False"
            SECRET_KEY: ${SECRET_KEY}
            ALLOWED_HOSTS: ${ALLOWED_HOSTS}
            CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS}
            DATABASE_URL: ${DATABASE_URL}
   
volumes:
    static_volume: {}

healthcheck:
  test: ["CMD", "curl", "-f", "http://localhost:8000"]
  interval: 1m30s
  timeout: 10s
  retries: 3
  start_period: 40s
  start_interval: 5s